config/routes.rb
Mybooks::Engine.routes.draw do
  resources :entries
  resources :accounts
  resources :books
end

app/models/mybooks/account.rb
module Mybooks
  class Account < ApplicationRecord
    belongs_to :book
  end
end

app/models/mybooks/application_record.rb
module Mybooks
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/mybooks/book.rb
module Mybooks
  class Book < ApplicationRecord
    has_many :accounts, dependent: :destroy
    has_many :entries, dependent: :destroy
    has_many :bank_statements, dependent: :destroy
    has_many :ofxes

    serialize :settings, HashWithIndifferentAccess
    attribute :recent


    def build_tree
      new_tree = []
      troot = self.accounts.find_by(uuid:self.root)
      troot.walk_tree(0,new_tree)
      new_tree.each do |a| 
        if a.level_changed?
          a.save
        end
      end
      new_tree
    end

    def destroy_book
      self.entries.destroy_all
      # self.bank_statements.destroy_all
      self.accounts.destroy_all
      self.destroy
    end


    def root_acct
      self.accounts.find_by(uuid:self.root)
    end

    def checking_acct
      self.accounts.find_by(uuid:self.checking)
    end

    def assets_acct
      self.accounts.find_by(uuid:self.assets)
    end

    def liabilities_acct
      self.accounts.find_by(uuid:self.liabilities)
    end

    def equity_acct
      self.accounts.find_by(uuid:self.equity)
    end

    def income_acct
      self.accounts.find_by(uuid:self.income)
    end

    def expenses_acct
      self.accounts.find_by(uuid:self.expenses)
    end

    def savings_acct
      self.accounts.find_by(uuid:self.savings)
    end

    def current_assets
      self.accounts.find_by(name:'Current')
    end



    def get_settings
      return {}.with_indifferent_access if self.settings[:skip].present? # on create new book
      reset = (Rails.application.config.x.acct_updated > self.updated_at.to_s || self.settings.blank?)
      # puts "DEBUG conf #{Rails.application.config.x.acct_updated}"
      # puts "DEBUG at #{self.updated_at.to_s}"
      # puts "DEBUG blank #{self.settings.blank?}"
      # puts "DEBUG reset #{reset}"

      if reset
        checking = checking_acct
        new_settings = {}.with_indifferent_access
        accts = build_tree
        id_trans = accts.pluck(:id,:transfer)
        if checking.present?
          new_settings[:checking_acct_id] = checking.id 
          new_settings[:checking_ids] = checking.leaf
        end
        new_settings[:transfers] = id_trans.to_h
        new_settings[:tree_ids] = new_settings[:transfers].keys
        new_settings[:acct_sel_opt] = id_trans.map{|i| i.reverse}.prepend(['',0])
        new_settings[:dis_opt] = accts.select{|a| a.placeholder}.pluck(:id)
        new_settings[:acct_sel_opt_rev] = new_settings[:acct_sel_opt].
          select{|i| i  unless new_settings[:dis_opt].include?(i[1])}.
          map{|i|[ i[0].split(':').reverse.join(':'),i[1]]}.
          sort_by { |word| word[0].downcase }
        self.settings = new_settings
        self.touch
        self.save!
      end
      return self.settings
    end
  end

  def self.create_book
    book = Book.new
    book.root = SecureRandom.uuid
    book.assets = SecureRandom.uuid
    book.liabilities = SecureRandom.uuid
    book.equity = SecureRandom.uuid
    book.income = SecureRandom.uuid
    book.expenses = SecureRandom.uuid
    book.checking = SecureRandom.uuid
    book.savings = SecureRandom.uuid
    settings = {skip:true}
    book.save


    broot = book.accounts.create(  
      {:name=>"Root Account",
       :account_type=>"ROOT",
       :description=>"",
       :parent_id=>nil,
       :placeholder=>true,
       :level=>0,
       :uuid=>book.root
    })

    bassets = book.accounts.create(
      {:name=>"Assets",
      :account_type=>"ASSET",
      :description=>"",
      :parent_id=>broot.id,
      :placeholder=>true,
      :level=>1,
      :uuid=>book.assets
      })

    bliabilities = book.accounts.create(
      {:name=>"Liabilities",
      :account_type=>"LIABILITY",
      :description=>"",
      :parent_id=>broot.id,
      :placeholder=>true,
      :level=>1,
      :uuid=>book.liabilities
    })

    bequity = book.accounts.create(
      {:name=>"Equity",
      :account_type=>"EQUITY",
      :description=>"",
      :parent_id=>broot.id,
      :placeholder=>true,
      :level=>1,
      :uuid=>book.equity
    })

    bincome = book.accounts.create(
      {:name=>"Income",
      :account_type=>"INCOME",
      :description=>"",
      :parent_id=>broot.id,
      :placeholder=>true,
      :level=>1,
      :uuid=>book.income
    })

    bexpense = book.accounts.create(
      {:name=>"Expenses",
      :account_type=>"EXPENSE",
      :description=>"",
      :parent_id=>broot.id,
      :placeholder=>true,
      :level=>1,
      :uuid=>book.expenses
    })

    bchecking = book.accounts.create(
      {:name=>"Checking",
      :account_type=>"BANK",
      :description=>"",
      :parent_id=>bassets.id,
      :placeholder=>false,
      :level=>2,
      :uuid=>book.checking
    })

    bsaving = book.accounts.create(
      {:name=>"Savings",
      :account_type=>"BANK",
      :description=>"",
      :parent_id=>bassets.id,
      :placeholder=>false,
      :level=>2,
      :uuid=>book.savings
    })
    self.settings = {}
    self.save
    self.get_settings
    true

  end
end

app/models/mybooks/entry.rb
module Mybooks
  class Entry < ApplicationRecord
    belongs_to :book
  end
end

app/models/mybooks/split.rb
module Mybooks
  class Split < ApplicationRecord
    belongs_to :account
    belongs_to :entry
  end
end

app/controllers/mybooks/accounts_controller.rb
module Mybooks
  class AccountsController < ApplicationController
    before_action :set_account, only: %i[ show edit update destroy ]

    # GET /accounts
    def index
      @accounts = Account.all
    end

    # GET /accounts/1
    def show
    end

    # GET /accounts/new
    def new
      @account = Account.new
    end

    # GET /accounts/1/edit
    def edit
    end

    # POST /accounts
    def create
      @account = Account.new(account_params)

      if @account.save
        redirect_to @account, notice: "Account was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /accounts/1
    def update
      if @account.update(account_params)
        redirect_to @account, notice: "Account was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /accounts/1
    def destroy
      @account.destroy
      redirect_to accounts_url, notice: "Account was successfully destroyed."
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_account
        @account = Account.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def account_params
        params.require(:account).permit(:uuid, :book_id, :name, :account_type, :code, :description, :placeholder, :contra, :parent_id, :level)
      end
  end
end

app/controllers/mybooks/application_controller.rb
module Mybooks
  class ApplicationController < ActionController::Base
  end
end

app/controllers/mybooks/books_controller.rb
module Mybooks
  class BooksController < ApplicationController
    before_action :set_book, only: %i[ show edit update destroy ]

    # GET /books
    def index
      @books = Book.all
    end

    # GET /books/1
    def show
    end

    # GET /books/new
    def new
      @book = Book.new
    end

    # GET /books/1/edit
    def edit
    end

    # POST /books
    def create
      @book = Book.new(book_params)

      if @book.save
        redirect_to @book, notice: "Book was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /books/1
    def update
      if @book.update(book_params)
        redirect_to @book, notice: "Book was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /books/1
    def destroy
      @book.destroy
      redirect_to books_url, notice: "Book was successfully destroyed."
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_book
        @book = Book.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def book_params
        params.require(:book).permit(:name, :root, :assets, :equity, :liabilities, :income, :expenses, :checking, :savings, :settings)
      end
  end
end

app/controllers/mybooks/entries_controller.rb
module Mybooks
  class EntriesController < ApplicationController
    before_action :set_entry, only: %i[ show edit update destroy ]

    # GET /entries
    def index
      @entries = Entry.all
    end

    # GET /entries/1
    def show
    end

    # GET /entries/new
    def new
      @entry = Entry.new
    end

    # GET /entries/1/edit
    def edit
    end

    # POST /entries
    def create
      @entry = Entry.new(entry_params)

      if @entry.save
        redirect_to @entry, notice: "Entry was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /entries/1
    def update
      if @entry.update(entry_params)
        redirect_to @entry, notice: "Entry was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /entries/1
    def destroy
      @entry.destroy
      redirect_to entries_url, notice: "Entry was successfully destroyed."
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_entry
        @entry = Entry.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def entry_params
        params.require(:entry).permit(:book_id, :numb, :post_date, :description, :fit_id, :lock_version)
      end
  end
end

app/helpers/mybooks/accounts_helper.rb
module Mybooks
  module AccountsHelper
  end
end

app/helpers/mybooks/application_helper.rb
module Mybooks
  module ApplicationHelper
  end
end

app/helpers/mybooks/books_helper.rb
module Mybooks
  module BooksHelper
  end
end

app/helpers/mybooks/entries_helper.rb
module Mybooks
  module EntriesHelper
  end
end

app/views/mybooks/entries/_entry.html.erb
<div id="<%= dom_id entry %>">
  <p>
    <strong>Book:</strong>
    <%= entry.book_id %>
  </p>

  <p>
    <strong>Numb:</strong>
    <%= entry.numb %>
  </p>

  <p>
    <strong>Post date:</strong>
    <%= entry.post_date %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= entry.description %>
  </p>

  <p>
    <strong>Fit:</strong>
    <%= entry.fit_id %>
  </p>

  <p>
    <strong>Lock version:</strong>
    <%= entry.lock_version %>
  </p>

</div>

app/views/mybooks/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :book_id, style: "display: block" %>
    <%= form.text_field :book_id %>
  </div>

  <div>
    <%= form.label :numb, style: "display: block" %>
    <%= form.text_field :numb %>
  </div>

  <div>
    <%= form.label :post_date, style: "display: block" %>
    <%= form.date_field :post_date %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :fit_id, style: "display: block" %>
    <%= form.text_field :fit_id %>
  </div>

  <div>
    <%= form.label :lock_version, style: "display: block" %>
    <%= form.number_field :lock_version %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mybooks/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render "form", entry: @entry %>

<br>

<div>
  <%= link_to "Show this entry", @entry %> |
  <%= link_to "Back to entries", entries_path %>
</div>

app/views/mybooks/entries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Entries</h1>

<div id="entries">
  <% @entries.each do |entry| %>
    <%= render entry %>
    <p>
      <%= link_to "Show this entry", entry %>
    </p>
  <% end %>
</div>

<%= link_to "New entry", new_entry_path %>

app/views/mybooks/entries/new.html.erb
<h1>New entry</h1>

<%= render "form", entry: @entry %>

<br>

<div>
  <%= link_to "Back to entries", entries_path %>
</div>

app/views/mybooks/entries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @entry %>

<div>
  <%= link_to "Edit this entry", edit_entry_path(@entry) %> |
  <%= link_to "Back to entries", entries_path %>

  <%= button_to "Destroy this entry", @entry, method: :delete %>
</div>